### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by ghost**
Tested working fine with sopel 7.x, so no reason to have the restrictive 6.x sopel requirement.

### CODE REVIEW

**Review by RhinosF1 — COMMENTED** [review]
Why not just up the 7 to 8?

**Comment by dgw** [comment]
Should squash that and make a proper commit message tbh

**Comment by surskitt** [comment]
Definitely worth adding, thanks for pointing this out. A more meaningful commit message would be appreciated, just mentioning the  new sopel version would be good enough I think.

**Comment by dgw** [comment]
It's mentioned "below the fold", but @xnaas may resist having to clone the repo and amend locally. I removed myself from the fork's access list after squashing, but am happy to do the reword if re-added.

Alternatively, @shanedabes can probably force-push to the head branch too, since "Allow edits from maintainers" is turned on by default for new PRs.

**Comment by surskitt** [comment]
OK it's fine, the commit body has enough information, I'll merge this.

Thanks again @xnaas .

I'll push a new hotfix version to pypi later today.

**Pull request merged**
