### PR TITLE
Reply with a non-scary error when no results.

### PR DESCRIPTION
**Pull request by ghost**
To a normal user, something like `Unexpected error (list index out of range) from xnaas at 2021-10-22 17:26:27.583027. Message was: .gif 6702v43702v43n702v4370v702v702v02v602v` isn't going to make any sense...instead: supply a useful error message.

### CODE REVIEW

**Comment by surskitt** [comment]
Looks fine, I've just cleaned it up a bit (doesn't seem like there's a point having the try/except on the whole section rather than just the part where we select from the array result).

What do you think?

**Comment by ghost** [comment]
I suppose there should really be an `except` for not being able to reach tenor as well.

**Comment by surskitt** [comment]
Yes, that wouldn't be caught by IndexError.

Just so you know, I don't use these modules any more, so they're not really maintained. Still, I'm obviously welcome to accept any PRs to fix my lazy code.

**Comment by ghost** [comment]
> Yes, that wouldn't be caught by IndexError.

Of course, was just thinkin' out loud. :P

Anyway, made another change and squashed.

Thoughts?

**Comment by surskitt** [comment]
Looks fine, I'll merge it and push a new release.

**Comment by surskitt** [comment]
Version 0.2.0 has your changes, thanks for the help!

**Comment by surskitt** [comment]
btw I mentioned I'm not using this stuff any more, I'm working on my own bot here: https://github.com/gowon-irc

Absolutely no documentation since I'm still messing about with it, but it's fun. Written in go and using separate processes talking to an mqtt broker.

**Comment by ghost** [comment]
> Version 0.2.0 has your changes, thanks for the help!

Awesome; thanks!

> btw I mentioned I'm not using this stuff any more, I'm working on my own bot here: https://github.com/gowon-irc

Not interested in golang (I don't even know Python, I just muddle through lol), but coolio. Good luck. :)

**Pull request merged**
